config/routes.rb
Rails.application.routes.draw do
  root "traffis_projects#index"
  resources :traffis_projects

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/traffis_project.rb
class TraffisProject < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/traffis_projects_controller.rb
class TraffisProjectsController < ApplicationController
  before_action :set_traffis_project, only: %i[ show edit update destroy ]

  # GET /traffis_projects or /traffis_projects.json
  def index
    @traffis_projects = TraffisProject.all
  end

  # GET /traffis_projects/1 or /traffis_projects/1.json
  def show
  end

  # GET /traffis_projects/new
  def new
    @traffis_project = TraffisProject.new
  end

  # GET /traffis_projects/1/edit
  def edit
  end

  # POST /traffis_projects or /traffis_projects.json
  def create
    @traffis_project = TraffisProject.new(traffis_project_params)

    respond_to do |format|
      if @traffis_project.save
        format.html { redirect_to traffis_project_url(@traffis_project), notice: "Traffis project was successfully created." }
        format.json { render :show, status: :created, location: @traffis_project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @traffis_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /traffis_projects/1 or /traffis_projects/1.json
  def update
    respond_to do |format|
      if @traffis_project.update(traffis_project_params)
        format.html { redirect_to traffis_project_url(@traffis_project), notice: "Traffis project was successfully updated." }
        format.json { render :show, status: :ok, location: @traffis_project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @traffis_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /traffis_projects/1 or /traffis_projects/1.json
  def destroy
    @traffis_project.destroy

    respond_to do |format|
      format.html { redirect_to traffis_projects_url, notice: "Traffis project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_traffis_project
      @traffis_project = TraffisProject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def traffis_project_params
      params.require(:traffis_project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/traffis_projects_helper.rb
module TraffisProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS3300Project2022</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/traffis_projects/_form.html.erb
<%= form_with(model: traffis_project) do |form| %>
  <% if traffis_project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(traffis_project.errors.count, "error") %> prohibited this traffis_project from being saved:</h2>

      <ul>
        <% traffis_project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/traffis_projects/_traffis_project.html.erb
<div id="<%= dom_id traffis_project %>">
  <p>
    <strong>Title:</strong>
    <%= traffis_project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= traffis_project.description %>
  </p>

</div>

app/views/traffis_projects/edit.html.erb
<h1>Editing traffis project</h1>

<%= render "form", traffis_project: @traffis_project %>

<br>

<div>
  <%= link_to "Show this traffis project", @traffis_project %> |
  <%= link_to "Back to traffis projects", traffis_projects_path %>
</div>

app/views/traffis_projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Traffis projects</h1>

<div id="traffis_projects">
  <% @traffis_projects.each do |traffis_project| %>
    <%= render traffis_project %>
    <p>
      <%= link_to "Show this traffis project", traffis_project %>
    </p>
  <% end %>
</div>

<%= link_to "New traffis project", new_traffis_project_path %>

app/views/traffis_projects/new.html.erb
<h1>New traffis project</h1>

<%= render "form", traffis_project: @traffis_project %>

<br>

<div>
  <%= link_to "Back to traffis projects", traffis_projects_path %>
</div>

app/views/traffis_projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @traffis_project %>

<div>
  <%= link_to "Edit this traffis project", edit_traffis_project_path(@traffis_project) %> |
  <%= link_to "Back to traffis projects", traffis_projects_path %>

  <%= button_to "Destroy this traffis project", @traffis_project, method: :delete %>
</div>